# Generated by Django 4.0.6 on 2023-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='image',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='accomodation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='cancelation_policy',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='property_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='requires_guest_phone_verification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='areadetails',
            name='area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generaldescription',
            name='description_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='ratings_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='bed_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='space_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
