# Generated by Django 4.0.6 on 2023-09-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accomodation_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacedetails',
            old_name='room_type',
            new_name='property_type',
        ),
    ]
