# Generated by Django 4.0.6 on 2023-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_room_type_spacedetails_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacedetails',
            old_name='property_type',
            new_name='room_type',
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
