# Generated by Django 4.0.6 on 2023-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_reviews_ratings_id_accomodation_ratings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='guests_included',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='maximum_night',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='minimum_nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='cleaning_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='extra_people_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='monthly_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='security_deposit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='weekly_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='check_in',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='cleanliness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='communication',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='location',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='accomodates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='bathroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='square_feet',
            field=models.IntegerField(null=True),
        ),
    ]
