# Generated by Django 4.0.6 on 2023-09-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_accomodation_guests_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadetails',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
