# Generated by Django 4.0.6 on 2023-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_areadetails_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadetails',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
