# Generated by Django 4.0.6 on 2023-09-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_areadetails_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='cleaning_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='extra_people_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='monthly_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='charge',
            name='security_deposit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='weekly_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
