# Generated by Django 4.0.6 on 2023-09-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_charge_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='maximum_night',
            new_name='maximum_nights',
        ),
    ]
