# Generated by Django 4.0.6 on 2023-09-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_maximum_night_accomodation_maximum_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='cancelation_policy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='requires_guest_phone_verification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='areadetails',
            name='neighbourhood',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='areadetails',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='amenities',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spacedetails',
            name='bed_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
