# Generated by Django 4.0.6 on 2023-09-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_accomodation_cancelation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacedetails',
            name='amenities',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
