# Generated by Django 4.0.6 on 2023-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_spacedetails_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
