# Generated by Django 4.0.6 on 2023-09-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='property_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='areadetails',
            name='zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
