# Generated by Django 4.0.6 on 2023-10-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_accomodation_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='available',
        ),
    ]
