# Generated by Django 4.0.6 on 2023-10-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_hostawaiting_tenant'),
        ('api', '0015_remove_calendar_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price_per_night', models.FloatField()),
                ('accomodation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.accomodation')),
                ('tenant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.tenant')),
            ],
        ),
    ]
