# Generated by Django 4.0.6 on 2023-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
