# Generated by Django 4.0.6 on 2023-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_neighbourhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_verifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='listings_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='response_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
