# Generated by Django 4.0.6 on 2023-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_alter_host_host_about_alter_host_host_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_location',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_neighbourhood',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_verifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='response_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
