# Generated by Django 4.0.6 on 2023-10-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_host_host_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
