# Generated by Django 4.0.6 on 2023-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAwaiting',
            fields=[
                ('host_awaiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('host_location', models.CharField(max_length=512, null=True)),
                ('host_about', models.TextField(blank=True, null=True)),
                ('host_neighbourhood', models.CharField(max_length=200, null=True)),
                ('host_verifications', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
